#!/bin/csh -f
#+
#
# L_sky_script_2
#
# Takes skies at a range of K-mirror angles.
# One sky is taken every 1 degree.
#
#-

camera narrow
sampmode 2
wait4ao off
filt Lp
tint  0.50
coadds  30
object lpsky
shutter open
echo "Starting Lp skies"
rotate   10.6 stationary
goi

rotate   11.1 stationary
goi

rotate   11.6 stationary
goi

rotate   12.1 stationary
goi

rotate   12.6 stationary
goi

rotate   13.1 stationary
goi

rotate   13.6 stationary
goi

rotate   14.1 stationary
goi

rotate   14.6 stationary
goi

rotate   15.1 stationary
goi

rotate   15.6 stationary
goi

rotate   16.1 stationary
goi

rotate   16.6 stationary
goi

rotate   17.1 stationary
goi

rotate   17.6 stationary
goi

rotate   18.1 stationary
goi

rotate   18.6 stationary
goi

rotate   19.1 stationary
goi

rotate   19.6 stationary
goi

rotate   20.1 stationary
goi

rotate   20.6 stationary
goi

rotate   21.1 stationary
goi

rotate   21.6 stationary
goi

rotate   22.1 stationary
goi

rotate   22.6 stationary
goi

rotate   23.1 stationary
goi

rotate   23.6 stationary
goi

rotate   24.1 stationary
goi

rotate   24.6 stationary
goi

rotate   25.1 stationary
goi

rotate   25.6 stationary
goi

rotate   26.1 stationary
goi

rotate   26.6 stationary
goi

rotate   27.1 stationary
goi

rotate   27.6 stationary
goi

rotate   28.1 stationary
goi

rotate   28.6 stationary
goi

rotate   29.1 stationary
goi

rotate   29.6 stationary
goi

rotate   30.1 stationary
goi

rotate   30.6 stationary
goi

rotate   31.1 stationary
goi

rotate   31.6 stationary
goi

rotate   32.1 stationary
goi

rotate   32.6 stationary
goi

echo "Finished Lp skies"
playsound -d
rotate 0
wait4ao on
