#!/bin/csh -f

obj phase_divers

# Take a grid of out of focus and in focus images to get phase
# diversity.
# Start at position [100,100].

#####
# Setup NIRC2
####
camera narrow
filt FeII
slit clear
grism clear
subc 1024
wait4ao off
pupil open
shutter open

#####
# Images
#####

rsh -l k2obsao k2aoserver modify -s ao OBSNNAME = 0.1trans
rsh -l k2obsao k2aoserver modify -s ao OBHPAON = 0

set dx = ( 0 310 310 0 -310 -310 0 310 310 )
set dy = ( 0 0 0 310 0 0 310 0 0 )  

set j = 1
while ( $j <= 25 )
	movefiber $dx[j] $dy[j]
	sleep 10

	echo $dx[j] $dy[j]

	# In Focus Image (65 sec each)
	sampmode 2
	tint 0.18
	coadd 10
	goi 3

	# Out of focus -2 mm (65 sec each)
	focusfiber -2
	sleep 3
	sampmode 3 2
	tint 2.0
	coadd 20
	goi 3

	# Out of focus -4 mm (65 sec each)
	focusfiber -2
	sleep 3
	sampmode 3 8
	tint 8.0
	coadd 5
	goi 3

	# Out of focus -6 mm (65 sec each)
	focusfiber -2
	sleep 3
	sampmode 3 16
	tint 16.0
	coadd 3
	goi 3

	# Return 
	focusfiber 6
	sleep 3
	
	@ j++
end

movefiber -620 -620
rsh -l k2obsao k2aoserver modify -s ao OBSFNAME = optnirc2

